# Generated by Django 4.0.4 on 2022-06-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=250)),
                ('sobre', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_menu', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=255)),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
                ('contato', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='', verbose_name='img')),
                ('descricao', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('palestrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornada22.palestrante')),
            ],
        ),
    ]
